"""add active column to customizations

Revision ID: 2f948b034560
Revises: 9a3e3a65318d
Create Date: 2026-01-01 23:19:24.232068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f948b034560'
down_revision = '9a3e3a65318d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('cake_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cake_shape', sa.String(length=50), nullable=True),
    sa.Column('cake_size', sa.String(length=50), nullable=True),
    sa.Column('cake_layers', sa.Integer(), nullable=True),
    sa.Column('flavor', sa.String(length=100), nullable=True),
    sa.Column('filling', sa.String(length=100), nullable=True),
    sa.Column('frosting', sa.String(length=100), nullable=True),
    sa.Column('is_gluten_free', sa.Boolean(), nullable=True),
    sa.Column('is_vegan', sa.Boolean(), nullable=True),
    sa.Column('is_sugar_free', sa.Boolean(), nullable=True),
    sa.Column('is_dairy_free', sa.Boolean(), nullable=True),
    sa.Column('toppings', sa.Text(), nullable=True),
    sa.Column('decorations', sa.Text(), nullable=True),
    sa.Column('message_on_cake', sa.String(length=200), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('customization_price', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cake_id'], ['cake.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_item_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_item_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cart_item_id'], ['cart_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customization_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customization_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('active')

    op.drop_table('cart_item_image')
    op.drop_table('cart_item')
    op.drop_table('cart')
    # ### end Alembic commands ###
