"""Add e-commerce models

Revision ID: 9a3e3a65318d
Revises: e531fd834bc8
Create Date: 2026-01-01 17:49:13.531431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3e3a65318d'
down_revision = 'e531fd834bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cake_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('default_shape', sa.String(length=50), nullable=True),
    sa.Column('default_size', sa.String(length=50), nullable=True),
    sa.Column('default_layers', sa.Integer(), nullable=True),
    sa.Column('default_flavor', sa.String(length=100), nullable=True),
    sa.Column('default_frosting', sa.String(length=100), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('primary_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('can_be_vegan', sa.Boolean(), nullable=True),
    sa.Column('can_be_gluten_free', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('orders_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customization_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_vegan_compatible', sa.Boolean(), nullable=True),
    sa.Column('is_gluten_free_compatible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cake_template_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['cake_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('cake_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cake_shape', sa.String(length=50), nullable=True),
    sa.Column('cake_size', sa.String(length=50), nullable=True),
    sa.Column('cake_layers', sa.Integer(), nullable=True),
    sa.Column('flavor', sa.String(length=100), nullable=True),
    sa.Column('filling', sa.String(length=100), nullable=True),
    sa.Column('frosting', sa.String(length=100), nullable=True),
    sa.Column('is_gluten_free', sa.Boolean(), nullable=True),
    sa.Column('is_vegan', sa.Boolean(), nullable=True),
    sa.Column('is_sugar_free', sa.Boolean(), nullable=True),
    sa.Column('is_dairy_free', sa.Boolean(), nullable=True),
    sa.Column('toppings', sa.Text(), nullable=True),
    sa.Column('decorations', sa.Text(), nullable=True),
    sa.Column('message_on_cake', sa.String(length=200), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('customization_price', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cake_id'], ['cake.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customization_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_column('active')
        batch_op.drop_column('image_url')
        batch_op.drop_column('description')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('delivery_address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('delivery_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('delivery_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('special_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('delivery_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['order_number'])
        batch_op.drop_constraint(batch_op.f('order_cake_id_fkey'), type_='foreignkey')
        batch_op.drop_column('special_requests')
        batch_op.drop_column('cake_id')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cake_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('special_requests', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('order_cake_id_fkey'), 'cake', ['cake_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('delivery_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('completed_at')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('special_instructions')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('discount')
        batch_op.drop_column('tax')
        batch_op.drop_column('delivery_fee')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('delivery_time')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('order_number')

    with op.batch_alter_table('customization_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('is_available')

    op.drop_table('order_item_image')
    op.drop_table('order_item')
    op.drop_table('cake_template_image')
    op.drop_table('customization_option')
    op.drop_table('cake_template')
    # ### end Alembic commands ###
